version: "3"

services:
  db:
    image: mysql:5.7
    container_name: sql_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=quotes_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3000:80

  backend:
    build: ./backend
    container_name: flask
    restart: always
    volumes:
      - ./backend/:/app
    expose:
      - 9000

  frontend:
    build: ./frontend
    container_name: vuejs
    restart: always
    expose:
      - 80

  server:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      #- "8080:8000"
      - "8080:80"
