version: "3"

services:
  server:
    build: ./server
    container_name: flask
    restart: always
    ports: 
      - 5000:5000
    expose:
      - 5000

  frontend:
    build: ./client
    container_name: node
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
