version: "3"

services:
  backend:
    build: ./server
    container_name: flask
    volumes:
      - ./db:/tmp
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000

  server:
    build: ./client
    container_name: node
    ports:
      - 8080:8080
    restart: always
    expose:
      - 8080
