version: '3.1'
services:
    app:
        container_name: app
        build:
            ./
        ports:
            - 5000:5000
        expose:
            - 5000
        environment: 
            - FLASK_DEBUG=1
            - FLASK_APP=app